# Bingo
A bingo card is a $5 \times 5$ matrix of cells, where each column is labelled with one letter of the word *BINGO* and each cell hosts a number (see [Bingo cards](https://en.wikipedia.org/wiki/Bingo_(American_version)#Bingo_cards)).  The range of numbers that can appear on the card is normally restricted by column, starting with the 'B' column hosting values in the $1 \dots 15$ range, the 'I' column hosting value in the $16 \dots 30$ range and so on and so forth until the 'O' column hosting values in the $61 \dots 75$ range (ranges are considered to be inclusive). Numbers cannot be repeated in a Bingo card. The central cell, i.e., the one in position `2,2` is a special free-cell, without a number, that is considered automatically filled.

A winning Bingo card contains a line of five numbers that have all been called while conducting draws for a lottery. Winning lines can either be orizontal, vertical or diagonal. The central free-cell is automatically filled, and thus it is possible to win after only four numbers have been actually drawn.

Write a program taking into account the following tasks:
1. Choose an appropriate data structure to represent a Bingo card in memory
2. Write a function that creates a random Bingo card and stores it your data structure of choice
3. Write a function that simulates a complete sequence of number draws
        3.1 A number must be drawn only once
        3.2 Only numbers between 1 and 75 are drawn
4. Write a function that given a sequence of drawn numbers, checks whether a given Bingo card is a winning one
5. Write a function that generate a Bingo card and a parametrized number `d` of potential draws, evaluating the minimum, maximum and average number of draws necessary to identify a winning configuration in the generated Bingo card.

In [7]:
import random
import itertools
import numpy as np
import copy

DIM=5
DECK=3
NUM=75
ATTEMPS=500
REF_WIN=[0,0,0,0,0]

def setBingoCard():
    bingo=dict()
    bingo["B"]=random.sample(range(1,16),DIM)
    bingo["I"]=random.sample(range(16,31),DIM)
    bingo["N"]=random.sample(range(31,46),DIM-1)  
    bingo["N"].insert(2,0) # inserte the free cell ( marked as 0 )
    bingo["G"]=random.sample(range(46,61),DIM)
    bingo["O"]=random.sample(range(61,76),DIM)
    return bingo

def createDeckCard():
    name="CARD_"
    deck=dict()
    for i in range(DECK):
        deck[name+str(i)]=setBingoCard() 

    return deck

def sequenceNumber():
    return random.sample(range(1,NUM+1),NUM)

def sequenceNumberN(n:int):
    return random.sample(range(1,NUM+1),n)

def checkValue(card:dict, value:int):
    for colonna in card.values():
        if value in colonna:
            i=colonna.index(value)
            del colonna[i]
            colonna.insert(i,0)

def checkWinMatrix(card:dict):
    mat=np.matrix(list(card.values())).transpose()
    #print(mat)
    result=[ True for e in range(DIM)  if np.all((mat[e,:])==0)]
        
    result+=[ True for e in range(DIM)  if np.all((mat[:,e])==0) ]        

    result+=[ True if  np.all((mat.diagonal())==0) else False]  

    result+=[ True if  np.all((np.fliplr(mat).diagonal())==0) else False]  

    return True if result.count(True)>=1 else False
    
def printWinnerMatrix(usersWinner:set,deck:dict):
    [ print(w,"\n",np.matrix(list(deck[w].values())).transpose(),"\n\n") for w in usersWinner ]


def game(deck:dict,sequence:list):
    win=False
    winner=set()
    for val in sequence:
        if not win:
            for idcard in deck.keys():
                checkValue(deck[idcard],val)
                win=checkWinMatrix(deck[idcard])
                if win :
                    winner.add(idcard)
    return winner

def statsForCard(card:dict,attemps:int):
    draws=dict()
    
    for i in range(attemps):
        c=copy.deepcopy(card)
        sequence=sequenceNumber()
        win=False
        for val in sequence:
            if not win:
                checkValue(c,val)
                win=checkWinMatrix(c)
                if win :
                    draws["draws_"+str(i)]=sequence.index(val)
    return draws



def main():
    deck    =createDeckCard()
    sequence=sequenceNumber()
    winner  =game(deck,sequence)


    print("Sequenza numeri vincenti: ",sequence)
    printWinnerMatrix(winner,deck)

    print("############################################")
    print("########    TESTING CARDS           ########")
    print("############################################")

    print("Card test:")
    ct=setBingoCard()
    print(ct)


    print("NUMBER ATTEMPS: ",ATTEMPS)
    stat=statsForCard(ct,ATTEMPS)

    minimo=min(stat.values())
    maximo=max(stat.values())
    avg=(maximo+minimo)/2

    print("Il minimo è:",minimo,"\nIl massimo è: ",maximo,"\nLa media è:",avg)


if __name__== "__main__" :
    main()



Sequenza numeri vincenti:  [66, 17, 54, 12, 74, 15, 69, 38, 65, 13, 6, 60, 4, 21, 3, 50, 10, 14, 58, 67, 52, 26, 7, 42, 63, 2, 24, 75, 36, 73, 64, 55, 22, 16, 49, 37, 40, 62, 30, 44, 8, 51, 34, 29, 56, 33, 1, 61, 70, 39, 71, 18, 68, 31, 27, 43, 47, 5, 53, 11, 46, 20, 9, 28, 35, 32, 19, 41, 72, 25, 57, 59, 23, 45, 48]
CARD_0 
 [[ 0  0  0  0  0]
 [ 0 28  0 59  0]
 [ 0 23  0  0  0]
 [ 9 27 41  0  0]
 [ 0  0  0  0  0]] 


CARD_2 
 [[ 0 25 39 46  0]
 [ 0 18  0 48  0]
 [ 0  0  0  0  0]
 [ 9  0  0  0  0]
 [ 0  0  0  0 68]] 


############################################
########    TESTING CARDS           ########
############################################
Card test:
{'B': [5, 4, 6, 14, 9], 'I': [24, 23, 28, 21, 30], 'N': [32, 38, 0, 42, 43], 'G': [51, 55, 58, 60, 54], 'O': [74, 65, 72, 75, 68]}
NUMBER ATTEMPS:  500
Il minimo è: 9 
Il massimo è:  65 
La media è: 37.0
