# Ex. 01
Given two NumPy arrays generate a first intermerdiary array with the sum of the two, and then compute the square root of each element of the latter.

## Example

- `a_1` = `[[1, 16, 1] [21 ,18, 27]]`
- `a_2` = `[[15 ,33, 24] [15 ,7, -2]]`
- `a_sum` = `[[16, 49, 25] [36, 25, 25]]`
- `a_sqrt` = `[[4, 7, 5] [6, 5, 5]]`



In [3]:
import numpy as np

a_1 = np.array([[1, 16, 1],[21 ,18, 27]])
a_2 = np.array([[15 ,33, 24],[15 ,7, -2]])

s= np.array(a_1+a_2)
print(s)

sqrt=np.sqrt(s)
print(sqrt,)


[[16 49 25]
 [36 25 25]]
[[4. 7. 5.]
 [6. 5. 5.]]


# Ex. 02

Given an input array, return a sub-array selecting only its odd rows and even columns.

## Example

- `in` = `[[3,6,9,12] [15,18,21,24] [27,30,33,36] [39,42,45,48] [51,54,57,60]]`
- `out` = `[[6 12] [30 36] [54 60]]`

In [4]:
input =np.array([[3,6,9,12], [15,18,21,24], [27,30,33,36], [39,42,45,48], [51,54,57,60]])

n_array=input[0::2,1::2]
print(n_array)   # utilizzo dello sliceing

[[ 6 12]
 [30 36]
 [54 60]]


# Ex. 03
Given an array in input, replace any elements bigger than `THRESHOLD` with `ANOTHER` value.

## Example

Let's assume `THRESHOLD = 50` and `ANOTHER = 0`
- `in` = `[75, 42, 60]`
- `out` = `[0, 42, 0]`

In [5]:
THRESHOLD=50
input= np.array([75,42,60])

input[input>THRESHOLD]=0

print(input)


[ 0 42  0]


# Ex. 04

Given a bi-dimensional NumPy array containing only ones, add a *frame* of zero values all around its borders.

## Hints
- You can solve this request *by-hand*
- You can solve this request using fancy indexing
- You can solve this request exploring the [built-in methods](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of `ndarray`

## Example

- `in` = `[[1 1] [1 1]]`
- `out`= `[[0 0 0 0] [0 1 1 0] [0 1 1 0] [0 0 0 0]]`

In [19]:
input=np.ones((4,4),dtype=int)

print(input)
x,y=np.shape(input)


out=np.insert(input,(0,x),0,axis=1)
out=np.insert(out,(0,y),0,axis=0)

print(out)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


# Ex. 05

Convert a given dictionary into a NumPy array.

After converting the sample dictionary below into an array, check its `dtype` and try to find its meaning in the [DOCS](https://numpy.org/doc/stable/reference/arrays.dtypes.html).

## Hints
In order to perform such a conversion, you have to procede in steps:
1. Fetch all the key-value pairs from the dictionary
2. Convert the previous result into a list
3. Pass the collected list as the `object` argument to the array constructor

## Example
```python
dict = {1: 'Dict',
        2: 'To',
        3: 'Array'}
```
becomes
```python
[['1' 'Dict']
 ['2' 'To']
 ['3' 'Array']]
```

In [48]:
dict = {1: 'Dict',
        2: 'To',
        3: 'Array'}

print(dict)
items=list(dict.items())
d2array=np.array(items)
print(d2array)

print(d2array.dtype)

# <U11
#  < -> little endian ;  U11 -> unicode String


{1: 'Dict', 2: 'To', 3: 'Arrayyyyyyy'}
[['1' 'Dict']
 ['2' 'To']
 ['3' 'Arrayyyyyyy']]
<U11


# Ex. 06

Create a bi-dimensional array of random values whose shape is (N,M). Identify the min, max, and average values within the generated array.

## Hints
- NumPy arrays expose a set of [built-in methods](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) that support the most common operations

In [80]:
import random

N=5
M=4
out= np.ndarray(shape=(N,M),dtype=int,buffer=np.random.randint(0,100,size=(1,N*M)))

print(out)

[[97 90 45 23]
 [87 63 91 52]
 [98 76 32 38]
 [23 29 85 88]
 [83 58 20  6]]


# Ex. 07
Create a 8x8 matrix filled with 0s and 1s in a checkerboard pattern.

## Hints
- You can solve this request expliting slicing
- You can solve this request using `np.tile`

In [89]:
schema=np.array([[0,1],[1,0]])
out= np.tile(schema,(10,10))
print(out)

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


# Ex. 08
Generate and normalize a 2d matrix of random samples.

## Hints
- Normalize the data by [standard-score](https://en.wikipedia.org/wiki/Standard_score)

In [107]:
out= np.random.random(size=(5,5))
print(out)
out=(out - np.mean(out))/(np.std(out))
print(out)

[[0.68842557 0.64031721 0.57695547 0.2033675  0.77916286]
 [0.13405325 0.2219509  0.29115232 0.4529009  0.0519702 ]
 [0.30289142 0.30333944 0.33741018 0.61242166 0.73472249]
 [0.80477804 0.90484319 0.03638472 0.62583954 0.26064871]
 [0.13281743 0.44012467 0.08080877 0.98070592 0.51899995]]
[[ 0.89111832  0.71523744  0.48359125 -0.88222093  1.22284767]
 [-1.1356291  -0.81428129 -0.56128563  0.03005619 -1.43571913]
 [-0.51836828 -0.51673033 -0.39217002  0.61325321  1.06037669]
 [ 1.31649503  1.68232641 -1.49269861  0.66230805 -0.67280475]
 [-1.14014718 -0.01665286 -1.3302873   1.95967535  0.27170979]]


# Ex. 09
Given a 1d array, negate all elements which are between `MIN` and `MAX`, in place.

## Hints
- You can use `<` and `>` to select elements in your arrays
- You can combine Boolean expressions together

In [111]:
out= np.random.randint(1,100,size=20)
print(out)
MIN=20
MAX=80

out[(out>MIN) & (out<MAX)]*=-1
print(out)


[82 63 30 17 59 30 72  8 66 20 69 63 31 91 86 30 47 75 90 46]
[ 82 -63 -30  17 -59 -30 -72   8 -66  20 -69 -63 -31  91  86 -30 -47 -75
  90 -46]


# Ex. 10
Write a generator function that returns the first N elements of the [Pell-Lucas sequence](https://en.wikipedia.org/wiki/Pell_number#Pell%E2%80%93Lucas_numbers) and use it as source data to create an array.

## Hints
- You can use `np.fromiter`

In [175]:

def pell_Lucas():
    n_1,n_2 = 2,2
    yield n_2
    yield n_1
    while True:      
        yield 2*n_1+n_2
        n_1,n_2= 2*n_1+n_2,n_1

gen=pell_Lucas()
N=20
out=np.fromiter(gen,dtype=int,count=N)

print(out)

[       2        2        6       14       34       82      198      478
     1154     2786     6726    16238    39202    94642   228486   551614
  1331714  3215042  7761798 18738638]


# Ex. 11
Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

## Hints
- You may need to use `np.sqrt` and `np.arctan2`

In [213]:
out =np.random.randint(1,100,size=(10,2))
print(out)

X,Y=out[:,0],out[:,1]

#toPolar=

x=np.sqrt(X**2 + Y**2)
y=np.arctan2(Y,X)
print(x)
print(y)


[[ 7 96]
 [26  5]
 [39 71]
 [67 99]
 [27 50]
 [18 88]
 [64 76]
 [94 14]
 [67 37]
 [41 19]]
[ 96.25487001  26.47640459  81.0061726  119.54078802  56.82429058
  89.82204629  99.35793879  95.03683496  76.53757247  45.18849411]
[1.49800848 0.18998829 1.06849395 0.97583328 1.07566306 1.36903398
 0.87090346 0.14784937 0.50456044 0.43395337]


# Ex. 12
Considering two arrays with shape (1,N) and (N,1). Compute their sum using an iterator.

## Hints
- You may use `np.nditer`

In [261]:
N=5
a = np.random.randint(1,100,size=(1,N))
b = np.random.randint(1,100,size=(N,1))

print(a)
print(b)

it = np.nditer([a,b,None])

for e1,e2,z in it:
    z[...]=e1+e2

print(it.operands[2])

[[25 82 38 82 74]]
[[74]
 [11]
 [ 1]
 [31]
 [36]]
[[ 99 156 112 156 148]
 [ 36  93  49  93  85]
 [ 26  83  39  83  75]
 [ 56 113  69 113 105]
 [ 61 118  74 118 110]]
